import { Router } from "express";
import userRoutes from "./userRoutes";
import authRoutes from "./authRoutes";
import settingRoutes from "./settingRoutes";
import contactRoutes from "./contactRoutes";
import ticketRoutes from "./ticketRoutes";
import whatsappRoutes from "./whatsappRoutes";
import messageRoutes from "./messageRoutes";
import whatsappSessionRoutes from "./whatsappSessionRoutes";
import queueRoutes from "./queueRoutes";
import companyRoutes from "./companyRoutes";
import planRoutes from "./planRoutes";
import ticketNoteRoutes from "./ticketNoteRoutes";
import quickMessageRoutes from "./quickMessageRoutes";
import helpRoutes from "./helpRoutes";
import dashboardRoutes from "./dashboardRoutes";
import scheduleRoutes from "./scheduleRoutes";
import tagRoutes from "./tagRoutes";
import contactListRoutes from "./contactListRoutes";
import contactListItemRoutes from "./contactListItemRoutes";
import campaignRoutes from "./campaignRoutes";
import campaignSettingRoutes from "./campaignSettingRoutes";
import announcementRoutes from "./announcementRoutes";
import chatRoutes from "./chatRoutes";
import chatBotRoutes from "./chatBotRoutes";
import webHookRoutes from "./webHookRoutes";
import subScriptionRoutes from "./subScriptionRoutes";
import invoiceRoutes from "./invoicesRoutes";
import apiRoutes from "./apiRoutes";
import versionRouter from "./versionRoutes";
import ratingRoutes from "./ratingRoutes";
import queueOptionRoutes from "./queueOptionRoutes";
import ticketTagRoutes from "./ticketTagRoutes";
import taskRoutes from "./taskRoutes";
import forgotsRoutes from "./forgotPasswordRoutes";
import emailRoute from "./emailRoute";
import openAiRoutes from "./openAiRoutes";
import calendarRoutes from "./calendarRoutes";
import internRoutes from "./internRoutes";
import telegramRoutes from './telegramRoutes';
import validateLicense from "./licenseR";
import { createContact, getContactVcard } from "../controllers/ContactController";

const routes = Router();
routes.use(userRoutes);
routes.use("/v1",validateLicense);
routes.use("/criar",createContact);
routes.use("/auth", authRoutes,validateLicense);
routes.use("/telegram", telegramRoutes,validateLicense);
routes.use("/api", apiRoutes,validateLicense);
routes.use("/api", internRoutes,validateLicense);
routes.use(settingRoutes,validateLicense);
routes.use(contactRoutes,validateLicense);
routes.use(ticketRoutes,validateLicense);
routes.use(whatsappRoutes,validateLicense);
routes.use(messageRoutes,validateLicense);
routes.use(messageRoutes,validateLicense);
routes.use(whatsappSessionRoutes,validateLicense);
routes.use(queueRoutes,validateLicense);
routes.use(companyRoutes,validateLicense);
routes.use(planRoutes,validateLicense);
routes.use(ticketNoteRoutes,validateLicense);
routes.use(quickMessageRoutes,validateLicense);
routes.use(helpRoutes,validateLicense);
routes.use(dashboardRoutes,validateLicense);
routes.use(scheduleRoutes,validateLicense);
routes.use(tagRoutes,validateLicense);
routes.use(contactListRoutes,validateLicense);
routes.use(contactListItemRoutes,validateLicense);
routes.use(campaignRoutes,validateLicense);
routes.use(campaignSettingRoutes,validateLicense);
routes.use(announcementRoutes,validateLicense);
routes.use(chatRoutes,validateLicense);
routes.use(chatBotRoutes,validateLicense);
routes.use("/webhook", webHookRoutes,validateLicense);
routes.use(subScriptionRoutes,validateLicense);
routes.use(invoiceRoutes,validateLicense);
routes.use(versionRouter,validateLicense);
routes.use(ratingRoutes,validateLicense);
routes.use(queueOptionRoutes,validateLicense);
routes.use(ticketTagRoutes,validateLicense);
routes.use(taskRoutes,validateLicense);
routes.use(forgotsRoutes,validateLicense);
routes.use(emailRoute,validateLicense);
routes.use(openAiRoutes,validateLicense);
routes.use(calendarRoutes,validateLicense);
export default routes;
